### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'https://letterboxd.com/dave/list/official-top-250-narrative-feature-films/'

### ISSUE THREAD

**Issue by dmac91** [greyivy/plex-letterboxd#1]
node ./index.js --ip http://127.0.0.1:32400 https://letterboxd.com/dave/list/official-top-250-narrative-feature-films/
node:fs:601
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'https://letterboxd.com/dave/list/official-top-250-narrative-feature-films/'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at file:///C:/Users/D/Desktop/New%20folder/plex-letterboxd/index.js:19:18
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'https://letterboxd.com/dave/list/official-top-250-narrative-feature-films/'
}

Node.js v18.16.0

**Comment by greyivy** [comment]
The argument should be the path to a file containing one Letterboxd URL per line.
